version: '3'
networks:
    in_docker:
        driver: bridge

volumes:
    certbot-etc:
    certbot-var:
    web-root:
services:
    nginx:
        image: nginx:alpine 
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
            - ./nginx:/etc/nginx/conf.d
            - ./dhparams:/etc/ssl/certs
        networks: 
            - in_docker

    certbot:
        image: certbot/certbot
        depends_on: 
            - nginx
        networks: 
            - in_docker
        volumes: 
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        command: certonly --webroot --webroot-path=/var/www/html --email <YOUR_EMAIL> --agree-tos --no-eff-email --staging -d <YOUR_DOMAIN_NAME>
