version: '3.2'
networks:
    in_docker:
        driver: overlay
        attachable: true

volumes:
    web-root:
services:
    nginx:
        image: nginx:alpine 
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certs:/etc/letsencrypt
            - ./var:/var/lib/letsencrypt
            - ./root:/var/www/html
            - ./nginx:/etc/nginx/conf.d
            - ./dhparams:/etc/ssl/certs
        networks: 
            - in_docker
